VERSION="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GBK2EY4GRD7ECXRUSP5DFJRHCNJEFXP2E4PCUYWS43YPAFA6IHGFX6W3"
]

[DOCUMENTATION]
ORG_NAME="ZIMBA PHILANTHROPY INVESTMENTS"
ORG_DESCRIPTION="Security, Resilience and International Donation"
ORG_LOGO="https://raw.githubusercontent.com/Zimba2026/moeda.zfi/refs/heads/main/logo.png.png"

[[CURRENCIES]]
code="ZFI"
issuer="GBK2EY4GRD7ECXRUSP5DFJRHCNJEFXP2E4PCUYWS43YPAFA6IHGFX6W3"
name="ZIMBA PHILANTHROPY INVESTMENTS"
desc="Security, Resilience and International Donation"
image="https://raw.githubusercontent.com/Zimba2026/moeda.zfi/refs/heads/main/logo.png.png"
display_decimals=2
